### ISSUE TITLE
syntax change - could "" be strings and '' be runes?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#102]
Would it be possible to change the syntax so "" are strings and '' are runes?

**Comment by mattn** [comment]
Do you want that Anko become Go? :)

**Comment by MichaelS11** [comment]
Well, I do really like Go, plus Go is the Engine... :)

But really this is about trying to do something like:

```
a = "a string"
if a[0] == 'a' {
  println("this does not print but probably should")
}
```

**Comment by MichaelS11** [comment]
@mattn ,

Any thoughts about this and/or how you would like it to work?

**Comment by TrueFurby** [comment]
I think **anko**'s syntax should be kept as simple as possible. It's supposed to be scripting language.

What I would recommend is to keep only syntax with double quotes`"` and make the parser use single character string as rune for comparisons like in your example. So the following would print the message ok.

```go
a = "a string"
if a[0] == "a" {
  println("this does not print but probably should")
}
```

**Comment by MichaelS11** [comment]
Right now `a[0]` returns a rune, so either we should change that to return a string or we should change `'a'` to be a rune instead of a string. Not sure I really understand why Go put in runes, but since Go does have them, is it important to support them in some way for variables imported?

Any one else have any thoughts? @mattn ?

**Comment by mattn** [comment]
I wonder that there is something that we cannot do because anko does not have rune.

**Comment by TrueFurby** [comment]
So even my example I posted above should not print anything? It does not have runes.

**Comment by mattn** [comment]
I'm considering that there is possible to be something we doesn't notice.

**Comment by MichaelS11** [comment]
If runes are unwanted, I think the only choice is to have `a[0]` of a string return a string instead of a rune. If that is what you want, I can make a PR for it.

**Comment by MichaelS11** [comment]
PR for index returning string instead of rune:

https://github.com/mattn/anko/pull/115

**Comment by MichaelS11** [comment]
This should now be resolved

https://github.com/mattn/anko/pull/115
