### ISSUE TITLE
Release tagging?

### ISSUE THREAD

**Issue by floren** [mattn/anko#106]
It would be nice to have a release (version 0.1.0, if you like) at some point so those of us using anko in production can lock in on a specific version. The recent change from returning reflect.Value to returning interface{} meant I had to do some unexpected code changes. I've just transitioned our project to using 'dep', so if anko had releases it would make it easier to lock to a known-good version.

**Comment by MichaelS11** [comment]
How would this look/work? Do you mean have code branches?

Right now you can git a particular commit and vendor it for your program, this way you can manually choose when to pull updates. I personally tend to only update the code I have vendor when I run into a bug or need a new feature.

**Comment by TrueFurby** [comment]
@MichaelS11  Yeah you can always use specific commit version. However it's much simpler for users to differentiate by tagging commits with semantic versioning. This would make obvious difference between two versions with breaking changes. Although this make require  some kind of release process, ideally with changelogs.

Anko so far has no version tagged: https://github.com/mattn/anko/releases

**Comment by MichaelS11** [comment]
Doing full semantic versioning (on each commit) and full change logs is not a trivial amount of work, unless I am not understanding an easy way to do it? Like I mentioned in another post, I personally would like to see 95%+ code coverage testing first.

As far for doing a simple GitHub release version (with semantic versioning if wanted) sound good to me when it comes time. Is it time for one yet? Still seems like the project has some growth yet before a release version. I personalty am having some challenges with multidimensional arrays. Additionally I would like to see the len function for example, maybe more, moving into the standard syntax.

I guess what I am saying is that putting out a release feel like a commitment to me. A version of code that will be maintained and patched until the next release version. I am all for release version, just wondering if it is worth that work and commitment at this time?

**Comment by mattn** [comment]
Currently, anko is still experimental. For example, I want to remove try/catch statement.

**Comment by markbates** [comment]
Recently the builtins was changed and has broken a lot of things. Can you please start implementing version tags?

**Comment by markbates** [comment]
@mattn seriously, changing that package has buffalo and pop entirely. Can you either revert the change or start tagging when you release breaking changes. Please.

**Comment by MichaelS11** [comment]
I highly suggest checking out:
https://github.com/golang/dep
This will solve this issue without having versioning. It should also be moving into the official go tool soon.

I think most people (maybe all) want versioning, just don't think it is coming anytime soon. Best bet is finding another way of solving this issue in the meantime. If dep is not wanted, can also vendor the package, which works as well.

**Comment by mattn** [comment]
Tagged v0.0.1.

**Comment by mattn** [comment]
Sorry, I'll tame care about next breaking changes.
