### ISSUE TITLE
How to create new package

### ISSUE THREAD

**Issue by Raggaer** [mattn/anko#121]
Hello. I am trying to define a new package but I cant find the correct way of doing it, looking at the builtins folder I am trying:

```go
func main() {
	env := vm.NewEnv()
	anko_core.LoadAllBuiltins(env)
	env.Define("println", log.Println)
	c := env.NewPackage("cc")
	err := c.Define("test", 10)
	if err != nil {
		log.Fatalf("Define error: %v\n", err)
	}
	script := `
	var cc = import("cc")
	println(cc.test)
	`
	_, err = env.Execute(script)
	if err != nil {
		log.Fatal(err)
	}
}
```

However I keep getting package `cc` not defined.

**Comment by mattn** [comment]
currently, appending package dynamicaly was not supported. and NewPackage is a function to create new struct Package. now I added core.AddImportable. please use anko_core.AddImportable(c).
