### ISSUE TITLE
Alright to move packages out of builtins and into packages?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#122]
@mattn ,

Would like to move all the packages out of builtins and into packages. Before I do a lot of copy and pasting, wanted to ask if this is alright?

Here the code change besides the moving of all the packages:

https://github.com/MichaelS11/anko/commit/a2ae07bd69215933a36745d93d36feca4a4970c8

Here is some examples of how the code would work:

```
env := vm.NewEnv()
packages.DefineImport(env)
value, err := env.Execute("strings = import(\"strings\"); strings.ToLower(\"TEST\")")
```

```
env := vm.NewEnv()
packages.DefineImport(env)
packages.Packages["myPackage"] = map[string]interface{}{"blah": func() string { return "blah" }}
value, err := env.Execute("myName= import(\"myPackage\"); myName.blah()")
```

```
env := vm.NewEnv()
env.AddPackage("myName", map[string]interface{}{"blah": func() string { return "blah" }})
value, err := env.Execute("myName.blah()")
```

The folder with the code changes:

https://github.com/MichaelS11/anko/tree/master/packages

**Comment by MichaelS11** [comment]
The folder with the code changes:

https://github.com/MichaelS11/anko/tree/master/packages

**Comment by MichaelS11** [comment]
Corrected . to /

https://github.com/MichaelS11/anko/commit/ca432701928a36de45721c6f4e9517e9fae24ced

Note that inside the script, the import would work exactly as before.

**Comment by MichaelS11** [comment]
Simplified the naming of the files

https://github.com/MichaelS11/anko/tree/master/packages

**Comment by mattn** [comment]
I'm thinking this way have may have issue for build constraints. For example, os package separate some functions for appengine.

https://github.com/mattn/anko/tree/master/builtins/os

**Comment by mattn** [comment]
I'm okay to make utility function to register symbols easily (like your suggestion).

**Comment by MichaelS11** [comment]
Great, thank you.

Here is one way that appengine could be done:


## os.go:
```
package packages

import (
  "os"
)

func init() {
  Packages["os"] = map[string]interface{}{
    "Args": os.Args
    ...
  }
  handleAppEngine()
}
```


## os_appengine.go

```
// +build !appengine

package packages

import (
  "os"
  "reflect"
)

func handleAppEngine() {
  Packages["os"]["Getppid"] = reflect.ValueOf(os.Getppid)
}
```

**Comment by mattn** [comment]
I'm okay your suggestion. Let's go this change. BTW, Most motivation of this issue is making directory structure flatness?

**Comment by MichaelS11** [comment]
Yes, flatness as well as simplification, ease of use for people adding there own packages set, separation, and ease of building a custom set of available packages (might not want all packages available, like exec for example).

**Comment by MichaelS11** [comment]
Thanks @mattn !
