### ISSUE TITLE
require dryRun to check syntax

### ISSUE THREAD

**Issue by Chyroc** [mattn/anko#129]
`dryRun` parse the code , and run the `[]ast.Stmt` with `env`, but not really exec.

In simple cases, it is possible to store a set of already defined variables/functions. If there are no variables/functions appearing in the code, there is an error.

**Comment by MichaelS11** [comment]
@Chyroc 
Any thoughts on the PR?

**Comment by Chyroc** [comment]
emmmm....have no idea..

**Comment by MichaelS11** [comment]
@Chyroc ,

So we can close this?
