### ISSUE TITLE
TestInterrupts is flaky

### ISSUE THREAD

**Issue by mattn** [mattn/anko#136]
https://travis-ci.org/mattn/anko/builds/356702741?utm_source=github_status&utm_medium=notification

**Comment by MichaelS11** [comment]
Unfortunately, not surprised. Any ideas on better ways to do this? Maybe I will just increase the number of loops.

**Comment by mattn** [comment]
I don't surprised too. Just a note.

**Comment by MichaelS11** [comment]
Maybe https://github.com/mattn/anko/pull/140 will help?

**Comment by mattn** [comment]
@MichaelS11 Could you please try to make PR for this again?

**Comment by MichaelS11** [comment]
Yes. Also been trying to figure out if there is a better way.

**Comment by MichaelS11** [comment]
To update this issue, new PR https://github.com/mattn/anko/pull/149 was merged.

**Comment by MichaelS11** [comment]
@mattn 

Truly to be helpful, thought you might like to know the word you are probably looking for is flaky.

https://www.urbandictionary.com/define.php?term=flaky

**Comment by mattn** [comment]
Thanks.
