### ISSUE TITLE
Rework referencing and dereferencing code

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#138]
In https://github.com/mattn/anko/pull/140 added a couple of tests that need to be fixed.

Also the code in vmExprFunction that calls invokeLetExpr seems like it should not be needed. Would like to be able to pass a pointer to a variable and have the VM variable be updated. Not sure if that is possible or not, but seems like it should be possible.

There is probably more, but that is a starting place.

**Comment by mattn** [comment]
Thanks. Please note what is problem and what should be fixed.

**Comment by MichaelS11** [comment]
In https://github.com/mattn/anko/pull/140 added a couple of tests that need to be fixed.

Also the code in vmExprFunction that calls invokeLetExpr seems like it should not be needed. Would like to be able to pass a pointer to a variable and have the VM variable be updated. Not sure if that is possible or not, but seems like it should be possible.

There is probably more, but that is a starting place.
