### ISSUE TITLE
CONTRIBUTING file needed?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#146]
@mattn 

There seems to be a change on how you would like PRs done. Maybe a CONTRIBUTING file or a Wiki entry would be helpful to explain what you would like and would not like?

**Comment by mattn** [comment]
I think this is good idea for that anyone join to contribute to this project. But I don't native english speaker. Do you know good one to make a base of CONTRIBUING.md ?

**Comment by MichaelS11** [comment]
Having a hard time finding a good simple example. Most of them are very complicated. Here are a couple of the smaller ones, but still think they are bigger then needed.

https://github.com/gaocegege/maintainer/blob/master/CONTRIBUTING.md
https://gitlab.com/gitlab-org/gitlab-runner/blob/8a243fc2d4fb7a478b5aaae85dd2f0ef66d1a22c/vendor/github.com/coreos/go-systemd/CONTRIBUTING.md
