### ISSUE TITLE
Comment syntax

### ISSUE THREAD

**Issue by Chyroc** [mattn/anko#148]
I find that using `# comment` as a comment now, which is similar to python
does it also plan to support `''' comment '''`/`""" comment """`?

Or is the go/c syntax `// comment` or `/* comment */`?

**Comment by mattn** [comment]
For the note (for me): We must consider about heredoc for the futhre. backtick? triple double-quote like python?

**Comment by MichaelS11** [comment]
I suggest matching Go comment syntax

https://golang.org/ref/spec#Comments

**Comment by mattn** [comment]
I hope to keep `#` for shebang.
