### ISSUE TITLE
Major rework of expressions, ast, and parser?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#166]
What do you think about maybe doing a major rework of the ast naming and how the parser is setup? Do it similar like Go is doing? (Or find another well documented spec to use?) Rework the parser and split up the case statements for expressions into smaller chunks?

https://golang.org/ref/spec#Expression

Expression = UnaryExpr | Expression binary_op Expression .
UnaryExpr  = PrimaryExpr | unary_op UnaryExpr .

binary_op  = "||" | "&&" | rel_op | add_op | mul_op .
rel_op     = "==" | "!=" | "<" | "<=" | ">" | ">=" .
add_op     = "+" | "-" | "|" | "^" .
mul_op     = "*" | "/" | "%" | "<<" | ">>" | "&" | "&^" .

unary_op   = "+" | "-" | "!" | "^" | "*" | "&" | "<-" .

Was thinking it was not something that has to be done all at once, we can do parts at a time.

**Comment by mattn** [comment]
AST and structs is good I think. But current implementation of parser is bits adhok.

**Comment by MichaelS11** [comment]
Would be nice to see operator precedence, short-circuit if evaluation, clear EBNF documentation of the syntax, and smaller case statements. I think at least some of that is going to be difficult to do without some rework of both the AST and parser.

**Comment by MichaelS11** [comment]
Still more of this that can be done but got operator precedence added so going to close this out.

https://github.com/mattn/anko/pull/291
