### ISSUE TITLE
slice bounds: slice expands sometimes, out of range error other times

### ISSUE THREAD

**Issue by floren** [mattn/anko#178]
I'm a bit confused by the behavior of this code: 

```
a = make([]int, 2)

a[0] = 10
a[1] = 20
printf("%v\n", a)
a[2] = 30
printf("%v\n", a)
a[4] = 40
printf("%v\n", a)
```

It prints this:

```
[10 20]
[10 20 30]
8: index out of range
```

(see http://play-anko.appspot.com/p/05fd341ac9a532e97d1fed1f66f264ba479aa6ec for a runnable example)

Based on my limited exploration, it seems like assigning to `a[len(a)]` is ok, even though the slice was declared to be smaller than that, but assigning a value to `a[len(a)+1]` is not ok. Here's how I'd expect things to work:

```
a = make([]int, 2)
a[0] = 10   # ok
a[1] = 20   # ok
a[3] = 30   # not ok!
a += 30   # ok!
```

**Comment by MichaelS11** [comment]
Looks like it is working as expected. There is an auto append feature.

For example, this code should not error:
```
a = make([]int, 2)
for i = 0; i < 1000; i++ {
  a[i] = i + 1
}
```

**Comment by floren** [comment]
Ok, so to make sure I understand properly before I close the issue: it will auto-append if you specify an index immediately after the current end of the slice, but **not** any other index?

**Comment by MichaelS11** [comment]
Basically: if len(slice) == index then auto append else error

If you want, here is the code to look at:
https://github.com/mattn/anko/blob/master/vm/vmLetExpr.go#L107-L128
