### ISSUE TITLE
deleting type syntax?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#184]
So we have map delete key:
`delete(aMap, "aKey")`
Delete variable in current scope:
`delete(aVariable)`
`delete(aVariable, false)`
Delete first found variable in current scope or parent scopes:
`delete(aVariable, true)`

How should the syntax be for deleting type?
`deleteType(aType)`
`deleteType(aType, false)`
`deleteType(aType, true)`
or 
`deleteType(aType, false, "type")`
`deleteType(aType, true, "type")`

or something else?

**Comment by mattn** [comment]
Hmm, we can add this but not high priority.
