### ISSUE TITLE
To everyone using Anko, request for your use case of Anko

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#218]
Hello everyone!

Could you please reply with your use case of Anko? If you have a use case that is the same as someone else's, can just thumb up their use case.

Would be great to know your use case to better improve Anko.

**Comment by Raggaer** [comment]
Plugins for a website, handle some parts of a controller using Anko scripts =)

**Comment by gedw99** [comment]
Allow users to write their own code.
Then it's sent out to all devices.
So they can run their own logic.

E.g. a CMS

**Comment by gedw99** [comment]
Also I am using go wagon too.
Compile golang to WASM and run it inside go wagon anywhere. Even on mobiles

**Comment by c4s4** [comment]
I use Anko as a scripting language in a build tool named Neon: https://github.com/c4s4/neon/

**Comment by gedw99** [comment]
@c4s4 thankyou. thats super helpful to see its use case and potential !

**Comment by MichaelS11** [comment]
Created a list of programs using Anko

https://github.com/mattn/anko/wiki/Programs-using-Anko

**Comment by Lobarr** [comment]
I'm using anko in a distributed system blockchain application that allows users deploy their code to the blockchain and execute it as they like. Check it out https://github.com/gizo-network/gizo
