### ISSUE TITLE
CC-BY-CA is never "by Wikipedia"

### ISSUE THREAD

**Issue by bep** [mattn/anko#219]
Just a friendly heads-up. Im not the photographer, but I have thousands of images on Wikimedia Common and I get slightly annoyed when Wikipedia/Wikimedia get my Photo Credit.

So:

"(Picture licensed under CC BY-SA 3.0 by wikipedia)"

Is almost certainly not correct. I have not looked into the photo in question, but it has a photographer/copyright holder, I'm sure. The "attribution part" in the CC license is not there to give glory/applause to the hosting platform.

**Comment by mattn** [comment]
Thanks. This picture was located in https://commons.wikimedia.org/wiki/File:An_dango.jpg . I copyed from it to this repository. I am not familiar to CC, what should I do?

**Comment by bep** [comment]
"Picture licensed under CC BY-SA 3.0, photo by Ocdp" -- I don't see his full name there, so that is the best you can do. He (she) is the owner of that photo, not Wikipedia.

**Comment by mattn** [comment]
Thank you. I'll fix in later.

2018年4月24日(火) 19:33 Bjørn Erik Pedersen <notifications@github.com>:
