### ISSUE TITLE
REQUEST: Allow any primitive data type as map key

### ISSUE THREAD

**Issue by Hucaru** [mattn/anko#220]
Is it possible to allow all primitive data types to be used as a map key, not just `string`?

**Comment by MichaelS11** [comment]
Would like this as well. Some of the code has already been refactored to allow this. In some cases it can be done already. For example can import a non-string key map from outside of Anko and some operations can be done with it, but it can be quite tricky to use right now.

**Comment by MichaelS11** [comment]
PR:

https://github.com/mattn/anko/pull/258

@Hucaru 
Are we good? Can this be closed?

**Comment by Hucaru** [comment]
@MichaelS11 Tested; works well.

**Comment by MichaelS11** [comment]
@mattn 
Close this?
