### ISSUE TITLE
Bytecode

### ISSUE THREAD

**Issue by Lobarr** [mattn/anko#230]
Does anko compile to bytecode and would it be possible to execute bytecode in the vm?

**Comment by MichaelS11** [comment]
Seems beyond the scope of Anko

**Comment by Lobarr** [comment]
Okay, Thanks

**Comment by alaingilbert** [comment]
@Lobarr I made a "encoder"/"decoder" for anko.
So basically: `source -> ast -> encoded AST in binary file`
Then `encoded -> ast -> execute`
My goal was to have "close-source" sharable scripts that are executable at runtime.
Ping me, if you want to know more.
