### ISSUE TITLE
Append

### ISSUE THREAD

**Issue by Lobarr** [mattn/anko#232]
Is the support for append going to be included as a core builtin function?

**Comment by Lobarr** [comment]
Okay, thanks. 

I'm extending anko with new packages for my use case and I'm having troubles with passing anko functions as parameter to a package. How do you suggest I solve this problem?

Context - I'm trying to implement this function https://github.com/thoas/go-funk/blob/master/transform.go#L193 into anko

**Comment by MichaelS11** [comment]
What kind of function are you trying to pass in? Not sure where `funk` is coming from.

Here is a simple example of Anko function passing another Anko function, if that helps at all.

```
package main

import (
	"fmt"
	"log"

	"github.com/mattn/anko/vm"
)

func main() {
	env := vm.NewEnv()

	err := env.Define("println", fmt.Println)
	if err != nil {
		log.Fatalf("Define error: %v\n", err)
	}

	script := `
func runFunc (aFunc, input) {
	return aFunc(input)
}

func myFunc (input) {
	return input + 1
}

println(runFunc(myFunc, 2)) // 3
`

	_, err = env.Execute(script)
	if err != nil {
		log.Fatalf("execute error: %v\n", err)
	}

}
```

**Comment by Lobarr** [comment]
I'm trying to pass a function from anko as the second parameter of this function 
```
func Map(arr interface{}, mapFunc interface{}) interface{} {
	if !IsIteratee(arr) {
		panic("First parameter must be an iteratee")
	}

	if !IsFunction(mapFunc) {
		panic("Second argument must be function")
	}

	var (
		funcValue = reflect.ValueOf(mapFunc)
		arrValue  = reflect.ValueOf(arr)
		arrType   = arrValue.Type()
	)

	kind := arrType.Kind()

	if kind == reflect.Slice || kind == reflect.Array {
		return mapSlice(arrValue, funcValue)
	}

	if kind == reflect.Map {
		return mapMap(arrValue, funcValue)
	}

	panic(fmt.Sprintf("Type %s is not supported by Map", arrType.String()))
}
```
I get the error message "Map function's argument is not compatible with type of array"

**Comment by MichaelS11** [comment]
What this what you were looking for?

```
package main

import (
	"fmt"
	"log"

	"github.com/mattn/anko/vm"
)

func test(aFunc func(string) string, input string) string {
	return aFunc(input)
}

func main() {
	env := vm.NewEnv()

	err := env.Define("println", fmt.Println)
	if err != nil {
		log.Fatalf("Define error: %v\n", err)
	}

	err = env.Define("test", test)
	if err != nil {
		log.Fatalf("Define error: %v\n", err)
	}

	script := `
myFunc = func (data) {
	return "a" + data
}

println(test(myFunc, "b")) // ab
`

	_, err = env.Execute(script)
	if err != nil {
		log.Fatalf("execute error: %v\n", err)
	}

}
```

Also recommend checking out the tests, probably some more examples of what you are looking for:

https://github.com/mattn/anko/blob/master/vm/vmReturnsAndFunctions_test.go

**Comment by Lobarr** [comment]
Okay, thanks!

**Comment by Lobarr** [comment]
I defined a package type and called a function that returns a pointer to that type and got an error "cannot call type ...." how do I solve this problem?
