### ISSUE TITLE
Map evaluation

### ISSUE THREAD

**Issue by c4s4** [mattn/anko#239]
This script:

```golang
package main

import (
	"fmt"
	"github.com/mattn/anko/vm"
)

func main() {
	m := map[interface{}]interface{}{
		"foo": 1,
		"bar": 2,
	}
	fmt.Println(m["foo"])
	env := vm.NewEnv()
	err := env.Define("println", fmt.Println)
	if err != nil {
		panic(err)
	}
	err = env.Define("m", m)
	if err != nil {
		panic(err)
	}
	_, err = env.Execute(`println(m["foo"])`)
	if err != nil {
		panic(err)
	}
}
```

Produces following output:

```
$ go run test.go 
1
<nil>
```

I think this should output *1* and *1*.

This works as expected with following code:

```golang
package main

import (
	"fmt"
	"github.com/mattn/anko/vm"
)

func main() {
	m := map[string]int{
		"foo": 1,
		"bar": 2,
	}
	fmt.Println(m["foo"])
	env := vm.NewEnv()
	err := env.Define("println", fmt.Println)
	if err != nil {
		panic(err)
	}
	err = env.Define("m", m)
	if err != nil {
		panic(err)
	}
	_, err = env.Execute(`println(m["foo"])`)
	if err != nil {
		panic(err)
	}
}
```

Thus, I suspect this is a problem with *interface{}* and *string* types as keys.

**Comment by MichaelS11** [comment]
Anko supports maps with strings as keys. It has limited support for maps with other keys.

Also see:
https://github.com/mattn/anko/issues/220

**Comment by c4s4** [comment]
Note that keys **are** strings.

**Comment by c4s4** [comment]
OK, but this one has working example code.

**Comment by c4s4** [comment]
I think these issues are not exactly the same. One is about keys type being string only, the other is about type behind *interface{}* being discovered. In my example, keys are strings and Go is able to get the value because it gets the real type of the key, not the declared one.

**Comment by c4s4** [comment]
I have made a pull request to fix this issue. *Enjoy!*

**Comment by MichaelS11** [comment]
@mattn 
I think this can be closed.
