### ISSUE TITLE
Request new feature: add some new features.

### ISSUE THREAD

**Issue by xtlsoft** [mattn/anko#249]
I need to use `... a` syntax in function arguments in some cases.
example:
```
func test(...a){
   print(a)
}

test(1, 2, 3)
```
Can you add it?

Another, can you provide built-in `defer` support?
And, can a module extend another module?
Also, will you add a constructor support?
Then, will you support some sugars? Like `(a) -> {return a;}` or `testFunc :: (a) -> a`

**Comment by xtlsoft** [comment]
OK, I'll submit a pull request later.

**Comment by xtlsoft** [comment]
I haven't read the source code before, so I made several mistakes.

**Comment by xtlsoft** [comment]
Sorry, I think I need to improve my skills, and then I will be able to understand the parser.

**Comment by xtlsoft** [comment]
I tried this:

**Comment by xtlsoft** [comment]
I tried this:
```go
    env.DefineGlobal("create", func(e *vm.Env) interface{} {

		r := e.DeepCopy()

		r.Execute("init()")

		return r

	})
```
Then I tried:

```go
module Test{
    a = 0
    func test(ab){
        c.a = ab
    }
    func init(){
        print("aaa")
    }
}

c = create(Test)
c.test(100)
print(c.a, Test.a)
c.a = 100
```

But I got:

```
aaaExecute error: no member named 'a' for struct
exit status 4
```

**Comment by MichaelS11** [comment]
Did you look at the module example?

https://godoc.org/github.com/mattn/anko/vm#example-package--VmModules

**Comment by MichaelS11** [comment]
Here is some code that works that is kind of similar to your code, if that helps at all.
```
func main() {
	env := vm.NewEnv()

	err := env.Define("println", fmt.Println)
	if err != nil {
		log.Fatalf("define error: %v\n", err)
	}

	script := `
module Test {
    a = 0
    func test(ab){
        a = ab
    }
    func init(){
        println("aaa")
    }
}
    
c = Test
c.init()
c.test(100)
println(c.a, Test.a)
`

	_, err = env.Execute(script)
	if err != nil {
		log.Fatalf("execute error: %v\n", err)
	}
}
```

Output:
```
aaa
100 100
```

**Comment by xtlsoft** [comment]
Thank you for your reply but I have read the document and what I want is to "new" a module, not to copy the pointer.
So if there is some way to "new" a module, please let me know.
Thank you.

**Comment by MichaelS11** [comment]
Can you provide an example of what you want in Go, JavaScript or Python?

**Comment by MichaelS11** [comment]
@xtlsoft 
Can this be closed?

**Comment by xtlsoft** [comment]
Yes, and I found a special way to solve this problem.

Thank you very much.
