### ISSUE TITLE
Question: variable scope of 'else if' 

### ISSUE THREAD

**Issue by tesujiro** [mattn/anko#259]
Hello
I am new to Anko, and have a question.
There is a difference of variable scopes between `if` and `else if`.
For example:
~~~
> a=1
1
> if a==1 { b=1 } else if a==2 { b=2 }
1
> b
1:1 undefined symbol 'b'
~~~
The "if {}" block has a new scope.
But
~~~
> a=2
2
> if a==1 { b=1 } else if a==2 { b=2 }
2
> b
2
~~~
The "else if {}" block has the same scope as outer statements.
In vmStmt.go, "if {}" and "else {}" creates a new environment, but "else if {}" does not.
It is a bit strange for me, are there any reasons doing so?

**Comment by MichaelS11** [comment]
@mattn 

Added to PR

https://github.com/mattn/anko/pull/258
