### ISSUE TITLE
Question： range(m, n)

### ISSUE THREAD

**Issue by catplant** [mattn/anko#262]
why range(m, n) returns [m, m+1, ..., n-1, n] while range(n) returns [0, 1, ..., n-1]?
I think range(n) should be equal to range(0, n)

**Comment by mattn** [comment]
@MichaelS11 How do you think?

vim: range(1) => [0], range(1,3) => [1,2,3]
python: range(1) => [0], range(1,3) => [1,2]

**Comment by MichaelS11** [comment]
I think like Python is good:
range(stop)
range(start, stop[, step])

https://docs.python.org/3/library/functions.html#func-range

https://stackoverflow.com/questions/3895478/does-javascript-have-a-method-like-range-to-generate-a-range-within-the-supp

At least for the short term. Long term, probably should change how range works, at least internally. Making a range of say 0 to 1,000,000,000,000,000,000 would make a really big array.
