### ISSUE TITLE
Go 1.6 and status

### ISSUE THREAD

**Issue by prsolucoes** [mattn/anko#27]
Hi,

I dont find any contact here, so i decide write here.

How long this project is supported? 
It has an active development?
Everything is working fine with Go 1.6?

I want put it on my open-source project like Jenkins, but made with Go. I need a script language user make their script to deploy.

**Comment by mattn** [comment]
>How long this project is supported? 

maybe forever until I will die.

>It has an active development?

currently stable. but I will probably change language spec about error handling

https://github.com/mattn/anko/issues/24

>Everything is working fine with Go 1.6?

yes.

**Comment by prsolucoes** [comment]
wow, thanks :) Im using it on my project. Everything is working fine, but the functions on README file are not found, like println. I get missing symbol.

**Comment by prsolucoes** [comment]
I think none of anko builtin functions is available:

var os, exec = import("os"), import("os/exec")

Error:

Undefined symbol 'import'

Im using anko embed in my app.

**Comment by prsolucoes** [comment]
Forgot...after read source i solve the problem...thanks!
