### ISSUE TITLE
automatically expand return value

### ISSUE THREAD

**Issue by Chyroc** [mattn/anko#276]
## 0
```
var fmt = import("fmt")

func f() {
    return 1, 2
}

var x= f()

fmt.println(x)
```

got:
```
[1 2]
```

This is what it is now

## 1
```
var fmt = import("fmt")

func f() {
    return 1, 2
}

var x, y= f()

fmt.println(x)
fmt.println(y)
```

got:
```
[1 2]
Execute error: undefined symbol 'y'
```

expect 
```
x = 1
y = 2
```

## 2
and if 
```
func f() {
    return 1, 2, 3
}

var x, y= f()
```

expect error

**Comment by MichaelS11** [comment]
Did you check this after PR https://github.com/mattn/anko/pull/275 ?

0 - Should be the same.
1 - Should now be as you expected.
2 - Would be like 1 but no error. I don't think we need to add an error for it.

**Comment by Chyroc** [comment]
great!
