### ISSUE TITLE
The func keywoard

### ISSUE THREAD

**Issue by adriangrigore** [mattn/anko#296]
What do you think off removing the `func` keyword. Might make parsing a little bit weird but it's not impossible? I'm not aware of the performance hit.

```
// function
add (x) {
	println(x + 1)
}
add(3) // 4

sub(x) {
	println(x - 1)
}
sub(3) // 2
```

**Comment by mattn** [comment]
Anko is inspired from Go. So unfortunately, I will not remove func literal if there are no reason that I convinced

**Comment by MichaelS11** [comment]
Regardless, I do not think parsing is possible. Plus even if it was possible, the parsing would be incredibly difficult and a major pain.

There are reasons why the Go people wrote the language spec as it is. It is good to follow it as closely as possible.

**Comment by earncef** [comment]
It wouldn't make any difference to runtime performance. I don't think this change adds anything useful.

**Comment by adriangrigore** [comment]
Again, I'm not even sure it's a good idea, so saying no it's fine, it's just a personal curiosity. I enjoyed how functions are defined in shell language so I was thinking of doing something similar for myself at some point.

Parsing is not impossible, although a little bit less simple that's true and I haven't touched major cases, but, yeah, except saving those few keystrokes, there's no benefit and I can't comment of the performance issues

If the idea behind the language is to be Go inspired, I understand where you're coming from.

Anyway, it's a great project! :)

**Comment by MichaelS11** [comment]
@adriangrigore Thanks for sharing your thoughts. Glad you like the project. :)

Could you please close this issue?
