### ISSUE TITLE
Bugs in toInt, toFloat, toBool functions?

### ISSUE THREAD

**Issue by mmindenhall** [mattn/anko#30]
I have created a function in go that returns a uint32.  I then call toInt on that value in anko, which converts it to 0.  I think there's a bug in how this is currently defined:

```go
env.Define("toInt", func(v interface{}) int64 {
		nt := reflect.TypeOf(1)
		rv := reflect.ValueOf(v)
		if rv.Type().ConvertibleTo(nt) {
			return 0
		}
		return rv.Convert(nt).Int()
	})
```
For this to work, I think the return statements will need to switch positions ([see in playground](https://play.golang.org/p/oT56Lk3-3f), with added ability to handle converting strings).

BTW, `toFloat` and `toBool` also have this bug.  I'll submit a PR to fix all 3 (and add the capability to convert from string).

**Comment by mattn** [comment]
Do you want to convert string into int or uint32? Then use strconv package.

**Comment by mmindenhall** [comment]
The golang way is to use strconv.  Given that anko is less strict, I thought it would be a nice feature for `toInt` to handle converting strings as well as numeric types.  If you don't want to add that feature, no problem.  

The real problem here is that the return statements need to swap positions for this to work properly:

```go
	// this returns 0 if the type is convertible, and tries to convert if it's not!
	if rv.Type().ConvertibleTo(nt)
		return 0
	}
	return rv.Convert(nt).Int()

	// this works
	if rv.Type().ConvertibleTo(nt) {
		return rv.Convert(nt).Int()
	}
	return 0
```

As said above, `toFloat` and `toBool` also need to have return statements swapped in a similar manner.

**Comment by mattn** [comment]
Ah, you are right. will fix in later.
