### ISSUE TITLE
Subtraction syntax errors

### ISSUE THREAD

**Issue by floren** [mattn/anko#301]
Using the anko interpreter, this works:

```
> 2+1
3
```
But this doesn't:
```
> 2-1
1:2 syntax error: unexpected NUMBER
```
This is ok:
```
> 2 -1
1:3 syntax error: unexpected NUMBER
```
but not this:
```
> 2- 1 
1
```

**Comment by MichaelS11** [comment]
Thanks for the report. Will work on fixing this soon.

**Comment by MichaelS11** [comment]
Should be fixed in: https://github.com/mattn/anko/pull/302

**Comment by MichaelS11** [comment]
@floren Good to close?

**Comment by floren** [comment]
Yeah, seems good.

**Comment by MichaelS11** [comment]
@floren Wonderful. Could you please close it?
