### ISSUE TITLE
Imported `type` is not visible in child scope

### ISSUE THREAD

**Issue by ipsusila** [mattn/anko#309]
`vm` is initialized using the following method:
```go
//Host golang code
env := vm.NewEnv()
core.Import(env)
packages.DefineImport(env)
```

and when executing the following Anko script: 
```go
var time = import('time')

//work as expected
d1 = new(time.Duration)
println(d1)

func foo() {
    //work as expected
    println(time.Now())
    
    //error: "no namespace called: time"
    d2 = new(time.Duration)
    println(d2)
}

//call foo()
foo()
```
error happened when trying to create instance of `time.Duration` (variable `d2`) inside the function `foo`. Temporary workaround is adding `import` statement inside the function, but it won't be available inside its child scope, e.g. the following Anko script won't work due to similar reason:

```go
var time = import('time')

//work as expected
d1 = new(time.Duration)
println(d1)

func foo() {
    var time = import('time') //temporary workaround

    //work as expected
    d2 = new(time.Duration)
    println(d2)

    if d2 != nil {    
        //error: "no namespace called: time"
        d3 = new(time.Duration)
        println(d2)
    }
}

//call foo()
foo()
```

**Comment by MichaelS11** [comment]
Thank you for finding this issue. Welcome to test on new PR https://github.com/mattn/anko/pull/310 or can wait for merge.

**Comment by MichaelS11** [comment]
@ipsusila Please test and close if fixed.

**Comment by ipsusila** [comment]
@MichaelS11 Thank you. I've tested the latest commit and now it is working as expected.
