### ISSUE TITLE
panic in LetsStmt

### ISSUE THREAD

**Issue by traetox** [mattn/anko#316]
we saw a panic come out of a system that is running scripts in a customer system.  I haven't yet been able to get a script sample with the data that can cause the panic, but it happened multiple times.  It appears that the code isn't validating the size of the slice.

The offending piece of code is `runInfo.rv = rvs[len(rvs)-1]`

here is the backtrace snippet:

```
panic: runtime error: index out of range

goroutine 85 [running]:
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:161
+0x5d0e
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:61
+0x2ec2
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:367
+0x23ce
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:61
+0x2ec2
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:205
+0x4d09
vendor/github.com/mattn/anko/vm.(*runInfoStruct).runSingleStmt(0xc000020690)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:61
+0x2ec2
vendor/github.com/mattn/anko/vm.RunContext(0xab6dc0,
0xc00002a800, 0xaafe40, 0xc0002ee750, 0xc000220500, 0x600, 0x1,
0xc00004efa8, 0x6ffc46)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/vmStmt.go:19
+0x107
vendor/github.com/mattn/anko/vm.(*Env).ExecuteContext(0xc000220500,
0xab6dc0, 0xc00002a800, 0xc0002e7200, 0x58e, 0xc00011dda0, 0x0, 0x1,
0x0)
        /home/user/mygo/src/vendor/github.com/mattn/anko/vm/env.go:388 +0x15e
main.runScript.func1(0xc00000d8c0, 0xab6dc0, 0xc00002a800,
0xc000216280, 0xc00006eea0)
```

Anyone have any ideas on a script snippet that could invoke this piece of the interpreter code?  I am still trying to generate a test case.

**Comment by MichaelS11** [comment]
@traetox 

I suggest editing anko/vm/vmStmt.go right after case *ast.LetsStmt (should be line 112) and add something like `if len(len(stmt.RHSS)) < 1 { newStringError(stmt, "let statement right hand side is 0") }`. See if that keeps it from panic.

**Comment by traetox** [comment]
We have hammered our application as aggressively as we know how and can't make this panic happen again.  It only happened on a single system (albeit multiple times).  I don't want to say "bad memory" but I am running out of ideas.

I am going to put together a PR that does the above on a few places where the code could potentially panic (external logic might prevent it, but better to be safe than sorry).

Thank you for the help.

**Comment by MichaelS11** [comment]
Hmmm, weird. Wonder why.

In general, probably don't want to add a lot of code to prevent potential panics. In this particular case the issue is probably cause by code in another spot, so would rather fix the issue in that spot. Of course the problem with that is we do not know where that is.

**Comment by MichaelS11** [comment]
@traetox So not much to be done with this issue? Close it?

**Comment by traetox** [comment]
Yeah. Close it

**Comment by MichaelS11** [comment]
Could you close it?

**Comment by traetox** [comment]
can't reproduce, investigating other causes
