### ISSUE TITLE
Can't Unmarshal JSON to a map

### ISSUE THREAD

**Issue by mmindenhall** [mattn/anko#33]
Run in [anko playground](http://play-anko.appspot.com/p/77fd25388d707aae5c5cad02396fbcf575b3821d).

```go
json = import("encoding/json")

jsonTrans = `{"name": "ph_settings", "type": "anko_cmd"}`
println(jsonTrans)

out = {}
err = json.Unmarshal(toByteSlice(jsonTrans), &out)
if err != nil {
	println("unmarshal: ", err)
}
println("result: ", out)
```

**Comment by mmindenhall** [comment]
Any thoughts on what might be happening here?  I haven't dug into the source code, as I suspected the problem was somewhere in the lexer or yacc tool code.  But happy to help with a PR if you can point me in the right direction.

**Comment by mattn** [comment]
Still thinking fixing this. Please wait.
