### ISSUE TITLE
unknown field 'Structs' in struct literal of type ast.TypeStruct

### ISSUE THREAD

**Issue by dgrr** [mattn/anko#334]
In https://github.com/mattn/anko/blob/master/parser/parser.go.y#L693

For some reason it doesn't exist here
https://github.com/mattn/anko/blob/master/parser/parser.go#L2022

```
parser.go.y:693: undefined: ast.TypeStructType
parser.go.y:693: unknown field 'Structs' in struct literal of type ast.TypeStruct
```

**Comment by dgrr** [comment]
vi := &ast.TypeStruct{Kind: ast.TypeStructType} // Structs: $3}
    for k, v := range $3 {
      vi.StructNames = append(vi.StructNames, k)
      vi.StructTypes = append(vi.StructTypes, v)
    }
    $$ = vi```

**Comment by dgrr** [comment]
https://github.com/dgrr/anko/blob/master/parser/parser.go.y#L713

**Comment by MichaelS11** [comment]
Not sure why you are getting that error. Have you updated to the latest version? `go get -u github.com/mattn/anko`

**Comment by dgrr** [comment]
Well... `Structs` is not  defined on that structure

**Comment by MichaelS11** [comment]
Sorry, I am not following what the issue is. Do you have a code example of what is not working?

**Comment by dgrr** [comment]
On anko/parser
```bash
dgrr:xs 20:54:52 [master] $ rm parser.go
dgrr:xs 20:54:54 [master x] $ make
goyacc -o parser.go parser.go.y

conflicts: 193 shift/reduce, 211 reduce/reduce
gofmt -s -w .
dgrr:xs 20:54:55 [master !?] $ vim ^C
dgrr:xs 20:54:59 [master !?] $ go build
# github.com/mattn/anko/parser
parser.go.y:693: unknown field 'Structs' in struct literal of type ast.TypeStruct
```

**Comment by MichaelS11** [comment]
Maybe try deleting your Go ..\src\github.com\mattn directory and doing a fresh go get?

Works fine for me:

```
cd  ..\src\github.com\mattn\anko\parser\

goyacc.exe -o parser.go parser.go.y

conflicts: 193 shift/reduce, 211 reduce/reduce
```

**Comment by MichaelS11** [comment]
You are correct, having same issue

**Comment by MichaelS11** [comment]
Looks like I missed uploading some of the parser changes. Working on a fix.

**Comment by MichaelS11** [comment]
@dgrr Thank you for finding this.

https://github.com/mattn/anko/pull/335
