### ISSUE TITLE
Anko is not thread-safe to use from multiple goroutines

### ISSUE THREAD

**Issue by leonelquinteros** [mattn/anko#34]
I'm using Anko for a thread-safe project and i found that the VM isn't safe for multiple goroutines. 

I've forked and quickly fix the issue i have, but i found there is a lack of support for this on the package and no data race tests are present to detect these issues. 

But by running `go test -race ./...` from the root directory, you can find 1 data race found "by accident" on a test.

**Comment by mattn** [comment]
If you have a fix already, could you please send me pull-request?

**Comment by leonelquinteros** [comment]
I have to write some tests and check it out, because i've only fixed my use case, which is really small, i could send a fix for that but the package will still have data races.

I'll try to send you something soon.
