### ISSUE TITLE
How can I get the result

### ISSUE THREAD

**Issue by KangDuoLa** [mattn/anko#352]
How can I get the result, i want remote execute the script,but it's likes can not get the result,for example do "Println"

**Comment by mattn** [comment]
What do you mean `remote execute`?

**Comment by KangDuoLa** [comment]
I send script data to the device on the server for the device to execute. I want to get the return result of the device execution。

**Comment by KangDuoLa** [comment]
> What do you mean `remote execute`?

I send script data to the device on the server for the device to execute. I want to get the return result of the device execution。

**Comment by KangDuoLa** [comment]
Is it impossible to get the remote execution result? If so, I will think of other ways

**Comment by mattn** [comment]
It's possible if you write package to communicate the device.

**Comment by KangDuoLa** [comment]
What do I need to do？
