### ISSUE TITLE
1 line counts as 2

### ISSUE THREAD

**Issue by dhiltonp** [mattn/anko#39]
Sample script with a syntax error:

```
#!anko

func fib(n) {
  a, b = 1, 1
  f = []
  for i in range n {
    f += a
    b += a
    a = b - a
  }
  return f
}

println(fib(20))
```

You get this output:

```

$ ./anko fib-for.ank
fib-for.ank:11: syntax error: unexpected IDENT
```

The reported line is incorrect, the error is on line 6. The correct line can be found by doing (l.pos.Line-1)/2+1... but that just masks the underlying problem - somewhere a new line is double counted.

**Comment by mattn** [comment]
range is function. use `range(n)`.

**Comment by dhiltonp** [comment]
This isn't a report about code not working; this is a report about the error being wrong.

The error occurs on line 6, not line 11.

**Comment by questionpython** [comment]
hi.
i also have this problem.

`line1:
line2:
line3:
line4:wrong( "1\n2\t3" )`

but error text is : 

> _example/test.ank:7: Undefined symbol 'wrong'
why say line 7?

**Comment by mattn** [comment]
What the code did you write?

**Comment by questionpython** [comment]
wrong( "1\n2\t3" )

**Comment by questionpython** [comment]
**number line in error text is wrong.**
also @dhiltonp say to you. but you ......

tankx.

**Comment by questionpython** [comment]
Did you understand?

**Comment by mattn** [comment]
The link already expired.

**Comment by questionpython** [comment]
> [](http://uploadboy.me/db918p0vxht2/input.txt.zip.html)

> [](blob:http://www.ezyzip.com/4f2fa013-d868-4900-bf81-7b23b65a8db2)

**Comment by mattn** [comment]
Already fixed

**Comment by questionpython** [comment]
so now number line in error not have bug? you sure?

**Comment by mattn** [comment]
do it your self. why you ask many times. you are engineer, read code at the first before asking.
