### ISSUE TITLE
How add some changes!?

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#40]
hi.

**One :** 

for add a function just change `builtins/core.go` file?
example change `env.Define("print", fmt.Print)`
to : 
`env.Define("printnew", fmt.Print)`
`env.Define("print", fmt.Print)`

==============

**Two :** 

for make `\a` (as a new line) in string content what do?
just change `parser/lexer.go` file?

and example change :
`case 'n':`
`	ret = append(ret, '\t')`
`	continue`

to

`case 'n':`
`	ret = append(ret, '\t')`
`	continue`

`case 'a':`
`	ret = append(ret, '\n')`
`	continue`

yes?

**Comment by mattn** [comment]
I don't understand what you mean. What is printnew? And `\a` is bell not new line. If you still have issue, please reopen this.

**Comment by questionpython** [comment]
not important then \a what maen in another interpreter.
this just a test for add a changes!.

i want do 2 change but not work. help me to do this 2 changes.
