### ISSUE TITLE
Can not parse big int

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#41]
hi
**Can not parse big int**

example input : 

`print(5*99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999456456456456666666666666666666666666666666666666666666666666666666666666699999999999999999999999999999999999999)
`

error : 

> typein:1: strconv.ParseInt: parsing "99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999456456456456666666666666666666666666666666666666666666666666666666666666699999999999999999999999999999999999999": value out of range

**Comment by mattn** [comment]
I will support big int. But I won't support big int literal.

**Comment by questionpython** [comment]
tank you. i wait for you...

**Comment by mattn** [comment]
Already implemented https://github.com/mattn/anko/commit/16b29cb450fda37db464451128dc1ecd01371ec7

**Comment by questionpython** [comment]
so now
input = `print(5*99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999456456456456666666666666666666666666666666666666666666666666666666666666699999999999999999999999999999999999999)`

work?

**Comment by mattn** [comment]
Did you read my comment? https://github.com/mattn/anko/issues/41#issuecomment-275965044

Please read. And use big package.

```
var big = import("math/big")
n, _ = big.ParseFloat("99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999456456456456666666666666666666666666666666666666666666666666666666666666699999999999999999999999999999999999999", 10, 64, big.ToNearestEven)
```

**Comment by questionpython** [comment]
can not store big int in variable and print big int without import in interpreter?
mean auto can use big int in interpreter?

**Comment by mattn** [comment]
Have you thought about computer resources(ex memory) or CPU load? anko treat all of numbers as int64 as same as go.
