### ISSUE TITLE
How can add index name for every array value?!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#46]
hi
How can add index name for every array value?!
(mean `map` type)

example :  `[ 0:"start","name":"mattn","age":39,"child":[1,2,3,4,5,9:1] ]`

also need to in interpreter code return a array.

tank you.
please add this to source.

**Comment by mattn** [comment]
It's not array. It's hashmap.

![anko hashmap](http://go-gyazo.appspot.com/2a3f4c7e7aa0247a.png)

**Comment by questionpython** [comment]
Good.

hashmap is necessary then every value have a index name.
so need to add a new type , Derived from the array and hashmap.

i say then can a type(like map) can not have some value , index name?

example : `list={"name":"attn",1,5,6,7,8}`

output of variable = `map(
"name" : "attn",
0:1,
1:5,
2:6,
3:7,
4:8,
)`

**Comment by mattn** [comment]
I don't want to add the feature because I don't think it's useful.
