### ISSUE TITLE
how hidden interface[]{} text from output?

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#47]
hi
how can hidden interface[***]{**} text from output?

`> age=39`
`39`
`> var age=39`
`[]interface {}{39}`

----

`var age=39` why have output?

**Comment by questionpython** [comment]
`> list={"one":1}`
`map[string]interface {}{"one":1}`
`> print list["one"]`
`1nil`
now also print `nil` why? how can hidden this?

**Comment by mattn** [comment]
No, because var statement support multiple assignment. So output should display as array.

```
var a, b = 1, 2
println(a) # 1
println(b) # 2
```
And println return two elements. number of bytes written and error. then. output should be

```
> println(list["one"])
1
[]interface {}{2, interface {}(nil)}
```
