### ISSUE TITLE
Can not say me to use what to make this?!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#48]
hi
Very ashamed

example : `list={"name":"attn",1,5,6,7,8}`

i not want then you do this.
i want (me) do this. but need a help.
can not say  me to use what to make this?
mean how can store value in go?

tank you. good bye.

**Comment by njaremko** [comment]
It seems English isn't your first language. You should look over the go tutorial at:

https://tour.golang.org/welcome/1

**Comment by mattn** [comment]
closing
