### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by joncooper** [mattn/anko#5]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with anko. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable anko on @Sourcegraph by going to https://sourcegraph.com/github.com/mattn/anko and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by mattn** [comment]
Sorry, No.
