### ISSUE TITLE
Why Hashmap index name can not int or another type?!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#51]
hi
Why Hashmap index name can not int or another type?!

need change `parser.go.y` file : 
`expr_pair :
	STRING ':' expr
	{
		$$ = &ast.PairExpr{Key: $1.Lit, Value: $3}
	}`

> use `expr` for index name.

also `vm.go` and `expr.go` file need some changes!

please also check this.
tank you.

**Comment by mattn** [comment]
Because anko inspired by go and **javascript**.

**Comment by mattn** [comment]
And please STOP asking. Please read code before asking! If you have pull-request, you are welcome. But I don't want to ask for many questions.
