### ISSUE TITLE
What ^ operator?

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#52]
Hi
What is `^` operator? and what do?

`print(^5)` ==> `-6`
`print(^-5)` ==> `+4`

in source : `reflect.ValueOf(^toInt64(v))`
after search in google undrestand then this operator is `Bitwise XOR`
so what do `^` opeator in go?

**Comment by mattn** [comment]
>so what do ^ opeator in go?

PLEASE DONT ASK ME!
https://golang.org/ref/spec#Arithmetic_operators
