### ISSUE TITLE
Bug of Pow Operator!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#53]
Hi
Please Check this.

`example/test.ank` (input file) : `print(5**5)`

`vm/vm.go` file:

> `case "**":`
> `	if lhsV.Kind() == reflect.Float64 {`
> `		return reflect.ValueOf(math.Pow(toFloat64(lhsV), toFloat64(rhsV))), nil`
> `	}`
> `	print(toFloat64(lhsV))//added by me to test`
> `	print(" ** ")//added by me to test`
> `	print(toFloat64(rhsV))//added by me to test`
> `	print("\n")//added by me to test`
> `	print(math.Pow(toFloat64(lhsV),toFloat64(rhsV)))//added by me to test`
> `	print("\n")//added by me to test`
> `	return reflect.ValueOf(int64(math.Pow(toFloat64(lhsV), toFloat64(rhsV)))), nil`

=========

output : 

> `$ ./anko example/test.ank`
> `+5.000000e+000 ** +5.000000e+000`
> `+3.125000e+003`
> `3125`
> 

why output of pow is `3125` ?!!!

**Comment by mattn** [comment]
It is not issue report. Please explain what is problem. PLEASE DO NOT ask me.

**Comment by questionpython** [comment]
`5**2` in your interpreter is `3125`
but just output = `25`

so why output of `**`(pow) is wrong?

**Comment by questionpython** [comment]
you check bug?

**Comment by mattn** [comment]
Do you understand what is pow? This behavior is same as your favorite python.

![772ed73fbab347f9](https://cloud.githubusercontent.com/assets/10111/22478839/f4850964-e82e-11e6-9462-10cb64cf4d83.png)

Don't judge what is a bug just by your knowledge, please. And you should more study programming languages.
