### ISSUE TITLE
Need global() function for global variable in function!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#54]
Hi
test input : 
`age=2`
`func test(){`
`age=age*2`
`	print(age)`
`}`
`test()`
now in function , can access to all of out. but this is bad.

need a global() function to can get access variable out of func.
please add global() function to interpreter.

tank you.

**Comment by mattn** [comment]
anko is not your favorite python. so I don't add the function.
```
age=2
func test(){
    var age = age*2
    println(age) # 4
}
test()
println(age) # 2
```
You should know lexical scope. https://en.wikipedia.org/wiki/Scope_(computer_science)#Lexical_scope_vs._dynamic_scope

If you want to check the variable is defined or not in the scope, use `defined("name")`.

```
println(defined("unknown_variable")) # false
```

**Comment by mattn** [comment]
You have better to be care that many questions from you are sending as email  like spamming to the watchers of this repository.

**Comment by questionpython** [comment]
i need global() function , and this is spam? why? .
may very users need this.
so why not add ? :-(
please add.Please God help.
this also better for you
i want make a program with you interpreter.
Why not support your products?
Do not like your application to be popular?
