### ISSUE TITLE
Feature Request , Array and Map

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#56]
i have tree Feature Requset:

One
====
`var list=[1,2,3,4]`
`list[]=5` # now The variable output expected is [1,2,3,4,5]
`print(list)`

Two
====
`var list={5:45456}`

can not set index name as int or get value from function or .....
in go also can get index name from other types, but anko no...

Tree
====
i think need a new data type. i also help to make this.
Derived from the array and Maps
example with operator `<>`
some example : 

`var list= < 1,2,3,4,5 >`
`var list= < 1,2,3,4,5 , < 56789 > , 9 >`
`var list= < 1,2,3,4,5 , < 56789,"dfgdfg" >,9,"dfgdfdfg>`
`var list= < "name" : "anko" , "age" : 50 , "child" : < 1 , 2 , 3 , "4" , 5 > >`

**Comment by mattn** [comment]
# One

```
list = range(1,5)
println(list)
```

# Two

No, as I said in another issue, Anko is inspired by JavaScript. So literal `[]` mean array, and `{}` mean hashmap. use:
```
list = {"5":45456}
println(list["5"])
```

# Three (Please check your Tree is wrong english! Go to Google Translate)
It's possible.
```
list= [1,2,3,4,5]
list= [1,2,3,4,5,[56789],9]
list= [1,2,3,4,5, [56789,"dfgdfg"],9,"dfgdfdfg"]
list= {"name":"anko", "age":50 , "child":[1,2,3,"4",5]}
```
