### ISSUE TITLE
Bug of Pointer Variable

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#57]
you send me a sample code in : https://github.com/mattn/anko/issues/55

input : 
`var a = 1`
`p = &a`
`println(1***p)`

but this say error : 

>`anko$ ./anko input.txt`
`panic: reflect.Value.Addr of unaddressable value`
goroutine 1 [running]:
panic(0x78ab80, 0xc820075070)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
reflect.Value.Addr(0x76b840, 0xc820075010, 0x16, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:240 +0x8c
github.com/mattn/anko/vm.invokeExpr(0x7f6ad5c3ad20, 0xc8200de780, 0xc820096410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/compiler/go/src/github.com/mattn/anko/vm/vm.go:844 +0xc8af
github.com/mattn/anko/vm.invokeExpr(0x7f6ad5c3ad58, 0xc820070340, 0xc820096410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/compiler/go/src/github.com/mattn/anko/vm/vm.go:1199 +0xd30
github.com/mattn/anko/vm.invokeExpr(0x7f6ad5c3ad90, 0xc820096500, 0xc820096410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/compiler/go/src/github.com/mattn/anko/vm/vm.go:1315 +0x770d
github.com/mattn/anko/vm.RunSingleStmt(0x7f6ad5c3adc8, 0xc8200de7a0, 0xc820096410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/compiler/go/src/github.com/mattn/anko/vm/vm.go:130 +0x58f3
github.com/mattn/anko/vm.Run(0xc820070380, 0x3, 0x4, 0xc820096410, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/compiler/go/src/github.com/mattn/anko/vm/vm.go:95 +0x214
main.main()
	/home/compiler/go/src/github.com/mattn/anko/anko.go:144 +0xaa8

**Comment by mattn** [comment]
Already fixed https://github.com/mattn/anko/commit/295fa83ccfa8750309775979229446d8a4ce4d91
