### ISSUE TITLE
Feature Request , Array Map (Please Read)

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#58]
HI
why not add feature request? and just lock issues?
link : https://github.com/mattn/anko/issues/56

example One : 
`var list=[1,2,3,4]`
`list[]=5`# now The variable output expected is [1,2,3,4,5]
`list[]=8`# now The variable output expected is [1,2,3,4,5,8]
`list[]=9`# now The variable output expected is [1,2,3,4,5,8,9]
`list[]="hello"`# now The variable output expected is [1,2,3,4,5,8,9,"hello"]
`print(list)`

i want can after make variable , add some value to array.
but you say anko have `range(1,5)` :|

i not have big request. just small changes.
please read my request on page.
please............................................

**Comment by mattn** [comment]
No, it can do with `range(1,5)` I don't want to add new multiple way to do 1 thing. This is a reason that I respect to Go, and Go doesn't add multiple way to do 1 thing.

If you don't like behavior of anko, please make new programming language by your self.
