### ISSUE TITLE
Bug of Pointer Variable (Again Another Bug)

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#59]
after  `go get ....`  and  https://github.com/mattn/anko/commit/295fa83ccfa8750309775979229446d8a4ce4d91 

input :
`var a = 1`
`p = &a`
`println(1***p)`

also again another error : `input.txt:2:3 syntax error: unexpected '='`

fix this.

**Comment by questionpython** [comment]
i check also https://github.com/mattn/anko/commit/295fa83ccfa8750309775979229446d8a4ce4d91 , but also agian show error : 
`input.txt:2:3 syntax error: unexpected '='`

**Comment by mattn** [comment]
do `go get -u ....`

**Comment by questionpython** [comment]
what do `-u` argument?

**Comment by mattn** [comment]
why you ask me? find it your self. I'm not your teacher.

**Comment by lovelearncode** [comment]
@questionpython 
`var a = 1`
`p = &a`
`println(1***p)`
There are no bugs and problems in this case. :+1:
