### ISSUE TITLE
Stop Anko execution

### ISSUE THREAD

**Issue by tyler-sommer** [mattn/anko#6]
I'm looking for a way to stop or limit the time Anko can execute. I looked through the source but I could not find a way to do this.

Would it be possible to implement the ability to cancel Anko execution?

**Comment by mattn** [comment]
Could you please show me the usecase or small code you expected?

**Comment by xrash** [comment]
This was somewhat solved in https://github.com/mattn/anko/pull/20.

A mechanism to interrupt the execution was introduced, but it is statement-based, not time-based.

**Comment by tyler-sommer** [comment]
This is perfect, thanks @mattn and @xrash !
