### ISSUE TITLE
Order/Priority of Array item is Different?!

### ISSUE THREAD

**Issue by questionpython** [mattn/anko#60]
What Problem ?
===========

why every time then script run ,  Order/Priority of array item is Different?

----

Input : 
======

`list={"name":"anko","age":49,"child":{"name":"anko","age":40}}`
`print(list)`

----

Output : 
======

`$ ./anko input.txt`
>map[name:anko age:49 child:map[name:arshia age:anko]]

`$ ./anko input.txt`
>map[age:49 child:map[name:anko age:40] name:anko]

**Comment by mattn** [comment]
map prints the keys in a shuffled order. this is expected.

**Comment by lovelearncode** [comment]
this is a problem.
How can it be fix?

**Comment by mattn** [comment]
This is not a problem. So I won't fix.

https://play.golang.org/p/lobKOWG7vA

If you want to know why this behavior, see https://github.com/golang/go/issues/2630
