### ISSUE TITLE
Sort map keys

### ISSUE THREAD

**Issue by c4s4** [mattn/anko#65]
Hi again,

I would like to iterate on a map with string keys, in alpha order:

```golang
sort = import("sort")

m = {"foo": 1, "bar": 2}
for k in sort.Strings(keys(m)) {
	println(m[k])
}
```

But this produces an error : `test.ank:0:0 reflect: Call using []string as type []interface {}`

**Comment by mattn** [comment]
Thank you

**Comment by c4s4** [comment]
Thanks to you! Your fixes are very quick. Do you have time left to sleep?

Regards

**Comment by mattn** [comment]
>Thanks to you! Your fixes are very quick. Do you have time left to sleep?

No, now I'm writing entry about Vim for magazine. 💪
