### ISSUE TITLE
Suggest a Better Lexer Generator For Anko!

### ISSUE THREAD

**Issue by lovegolang4fun** [mattn/anko#66]
Hello,

Flex(GoLex)
---------

i think is better then you use from `golex` (flex), its fast and easy.

Main: https://github.com/cznic/golex/
Sample: https://github.com/cznic/golex/tree/master/calc - https://godoc.org/github.com/cznic/ebnf2y
Comment : `golex -h`(generate lexer) , `goyacc -h`(generate yacc)

I'm waiting for you...
I hope this is helpful to do as soon as possible.

please do it.
Thanks a lot.

**Comment by mattn** [comment]
Thank your suggestion. But I decide that anko don't depend on third party command or packages as much as possible. (I know there are some package dependencies in anko). Sorry.

**Comment by lovegolang4fun** [comment]
Why? , `GoLex` not package , in a generator. so not problem.
and can use from this generator.
this easy and `Fast`.

please do this.
tank you very much. :+1:

**Comment by mattn** [comment]
Anko is experimental project to confirm what I can do with golang. So I will decide what code I should add code into anko.

**Comment by lovegolang4fun** [comment]
Hello, sir
Now the project is ANKO has little power to maintain location for error.
And to address cases like this better manufacturer to be used like GOLEX.(use from `GOLEX` as lexer)
However you agree that use it?

**Comment by mattn** [comment]
I say again, Project anko is experimental project to confirm what I can do with golang. If goyacc have problem, I'll fix goyacc it self.
