### ISSUE TITLE
Anko no longer supports < 1.8

### ISSUE THREAD

**Issue by markbates** [mattn/anko#68]
This commit: https://github.com/mattn/anko/commit/9e581b751c2e001e4035bfcff3d9731fc430b7bc broke support for versions of Go less than 1.8. Typically, projects try to support the current version, plus the previous version. 

This ticket is really to confirm that you meant to stop supporting <= 1.7. Please confirm.

**Comment by TrueFurby** [comment]
Which part breaks it? Some new feature in `reflect`?

**Comment by markbates** [comment]
sort.Slice is only in 1.8

**Comment by TrueFurby** [comment]
So simple *[build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints)* should fix this for older version, right?

**Comment by markbates** [comment]
Should do, yeah.

**Comment by TrueFurby** [comment]
Maybe you can add more versions to [.travis.yml](https://github.com/mattn/anko/blob/master/.travis.yml), so it will detect similar issues in the future.

**Comment by mattn** [comment]
make sense. https://travis-ci.org/mattn/anko/builds/214974831
