### ISSUE TITLE
keys() builtin function

### ISSUE THREAD

**Issue by c4s4** [mattn/anko#73]
Hi Mattn,

If I define a map such as:

```golang
m = {"foo": 1, "bar": 2}
```

Then I evaluate following code:

```golang
keys(m)
```

This should return a slice of strings with key names, but instead, I get:

```golang
[]string{"<interface {} Value>", "<interface {} Value>"}
```

Which is obviously wrong. I have had a look at the code for keys() function, and it returns a slice of strings, which sounds strange to me. If I replace your code with the following (which return a slice of reflect.Value) one:

```golang
env.Define("keys", func(v interface{}) []reflect.Value {                    
    rv := reflect.ValueOf(v)
    if rv.Kind() == reflect.Interface {
        rv = rv.Elem()
    }
    if rv.Kind() != reflect.Map {
        panic("Argument #1 should be map")
    }
    return rv.MapKeys()
})
```

Everything works fine.

**Comment by mattn** [comment]
SGTM, could you please send me pull-request?
