### ISSUE TITLE
Error in example script server.ank

### ISSUE THREAD

**Issue by TrueFurby** [mattn/anko#86]
Running script [server.ank](/mattn/anko/blob/master/_example/scripts/server.ank) fails with following error.
```
_example/scripts/server.ank:0:0 reflect: Call using interface {} as type http.Handler
```
It seems it doesn't allow `nil` value as parameter for `ListenAndServe` function.

**Comment by mattn** [comment]
This seems to be regression in ffb85afbeda0719bfbe4c5dbcd7ada499e198583

@MichaelS11 can you handle this?

**Comment by mattn** [comment]
https://github.com/mattn/anko/commit/56be449430a3e112f9b1871b6cd6bf748a3527de#diff-89570c464637c8d662a375fdd8f47b90R13

This change seems wrong.

**Comment by TrueFurby** [comment]
@MichaelS11 please include some test cases for this type of calls

**Comment by MichaelS11** [comment]
Added tests and corrected function nil handling

https://github.com/mattn/anko/pull/92
