### ISSUE TITLE
why '>' GE '<' LE  are %left?

### ISSUE THREAD

**Issue by nati** [mattn/anko#9]
I have a question about parser about '>' GE '<' LE.
Not it looks like this

%nonassoc EQEQ NEQ ','
%left '>' GE '<' LE SHIFTLEFT SHIFTRIGHT

if( 3 > 2 > 1){
  println("true")
}else{
  println("false")
}

This code prints "false".
IMO this should be

%nonassoc EQEQ NEQ ','  '>' GE '<' LE 
%left SHIFTLEFT SHIFTRIGHT

**Comment by mattn** [comment]
```
if( 3 > 2 > 1){
    println("true")
}else{
    println("false")
}
```
This mean
```
if((3 > 2) > 1){
    println("true")
}else{
    println("false")
}
```
so
```
if(1 > 1){
    println("true")
}else{
    println("false")
}
```
then
```
false
```

**Comment by nati** [comment]
Thank you for your reply.
I got it. This looks like same behavior with javascript.
