### ISSUE TITLE
Questions about multidimensional arrays

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#93]
1) How do you build a multidimensional of zero length?

// Trying to get the output [][]interface{}{}
a = [[]]
len(a) // is 1, want 0

2) How do you build the array [[1,2],[3,4]] from empty multidimensional array with append?

// Want code something like the following but the following code does not work
a = [[]]
a += [1,2]
a += [3,4]

**Comment by mattn** [comment]
it should be `[]`?

```
a = []  # This is non-typed slice sized 0
a += [[1,2]] # Add item into the slice as 1 element
a += [[3,4]] # Add item into the slice as 1 element
println(a)
[[1 2] [3 4]]
```

**Comment by MichaelS11** [comment]
Thanks for your help. I am trying to get the same type of multidimensional array no matter the input. 

Example with wanted multidimensional array:

```
output = []
input = [1,2,3,4]
for i = 1; i < len(input); i += 2 {
  output += [[input[i-1],input[i]]]
}
println(output) // [[1 2] [3 4]]
```


Example with unwanted single dimensional array:

```
output = []
input = []
for i = 1; i < len(input); i += 2 {
  output += [[input[i-1],input[i]]]
}
println(output) // []
```
Want output to be:
`[[]]`

**Comment by mattn** [comment]
len(input) always return 0 in your example. So your loop never run.

**Comment by MichaelS11** [comment]
For the first example, it would return 4, but yes, for the second example it would return 0. That is the idea.

Say the input was from some user input that is unknown ahead of time. If there is no input data, still want the output to be a multidimensional array.

**Comment by mattn** [comment]
Sorry, I don't still understand what is your issue. Anko's slice works like Python's one.

```
Python 2.7.14 (default, Nov  9 2017, 09:50:21)  [GCC 7.2.0 64 bit (AMD64)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = []  # This is non-typed slice sized 0
>>> a += [[1,2]] # Add item into the slice as 1 element
>>> a += [[3,4]] # Add item into the slice as 1 element
>>> print(a)
[[1, 2], [3, 4]]
>>>
```

**Comment by MichaelS11** [comment]
Thank you :)
