### ISSUE TITLE
Feature request - parse error for var with mismatched count

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#95]
The following is currently valid code.

```
var a, b = 1, 2, 3
var a, b, c = 1, 2
```

Could you do a Anko code change to make the above code give a parse error?

(I have not figured out the parsing code yet to do a PR.)

**Comment by MichaelS11** [comment]
Also could these mismatches become syntax errors as well?

`
a, b = 1, 2, 3
a, b, c = 1, 2
`

**Comment by mattn** [comment]
https://github.com/mattn/anko/pull/97 is depend on this issue?

**Comment by MichaelS11** [comment]
https://github.com/mattn/anko/pull/97 does not depend on this issue. I was going to do another PR after this issue was completed to do some cleanup if you wanted.

**Comment by mattn** [comment]
This is difficult to raise error while parsing because 

```
out, err = exec.Command("foo").Output()
```

This is varid even if count of rhs is not same as count of lhs. Anko is script language. So this is difficult to raise an error while parsing. But it's possible to do while runtime.

**Comment by MichaelS11** [comment]
I hear what you are saying. I think raising an error while parsing is not possible at all because a variable can change types, from whatever into a function. So the problem would be something like the following:
(Variables are set outside of the script)
```
if (a == b) {
  out, err = foo()
} else {
  data = foo()
}
```

On a side note, what is the difference between var `a, b = 1, 2` and `a, b = 1, 2`. Why are there two areas in the vm code for this? From what I can tell, `var out, err = aFunc()` would not work correctly, right?

**Comment by MichaelS11** [comment]
@mattn ,

What is the difference between `var a, b = 1, 2` and `a, b = 1, 2`? Are two areas in the vm code needed?

**Comment by MichaelS11** [comment]
Think is now sorted.
